pref( "extensions.snapper.displayIcon", true );
pref( "extensions.snapper.mode", 2 );
pref( "extensions.snapper.saveLocation", "" );
pref( "extensions.snapper.saveType", 2 );
pref( "extensions.snapper.autoSave", false );
pref( "extensions.snapper.snappingMode", 1 );
pref( "extensions.{fab752b0-f83e-11da-974d-0800200c9a66}.description", "chrome://snapper/locale/snapper.properties" );
pref( "extensions.snapper.disableNotifications", false );
pref( "extensions.snapper.editSnappedImage", false );